version: '2'
services:
    churn-app:
        image: churn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://churn-mysql:3306/churn?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    churn-mysql:
        extends:
            file: mysql.yml
            service: churn-mysql
